#!/usr/bin/env python3
import os, sys
import pyturbocat

if __name__ == '__main__':

	# Initialize the application object
	app = pyturbocat.Application()

	# Initialize modules
	from pyturbocat.web import Module
	app.module_init(Module)

	# Execute
	ret = app.run()

	sys.exit(ret)
